# Numpy

Numpy è un modulo che gestisce e manipola array di numeri.

Permette di svolgere operazioni tra tutti gli elementi con una sola istruzione facendo risparmiare molte linee di codice. In questo modo lo stile del codice eviterà diversi *loop* uno dentro l'altro favorendo una scrittura più lineare ed in genere fornisce implementazioni più veloci.

A differenze delle liste python, **il tipo di dati è fisso** in numpy perché usa aree di memoria contigue. Questo rende l'implementazione più rapida delle liste usuali. 

* <a href="https://numpy.org/">documentazione</a>

* <a href="https://youtu.be/GB9ByFAIAH4">tutorial online</a>

In [2]:
import numpy as np
import math

In [3]:
x = np.array([2, 5, 6])
y = np.array([3, 7, 8])
xy = x+y
print(xy)

[ 5 12 14]


Definiamo una matrice di rotazione di un angolo $\theta = \pi/3$:

In [14]:
theta = math.pi/3
st = math.sin(theta); ct = math.cos(theta)
rot = np.array([[ct, st],[-st, ct]])
print(rot)
print("dimensions: ", rot.ndim)
print("rows, cols: ", rot.shape)
print("data type: ", rot.dtype)

[[ 0.5        0.8660254]
 [-0.8660254  0.5      ]]
dimensions:  2
rows, cols:  (2, 2)
data type:  float64


In [15]:
rot11 = rot[0,0]; rot12 = rot[0,1]
rot21 = rot[1,0]; rot22 = rot[1,1]
print(rot11, rot12)
print(rot21, rot22)

0.5000000000000001 0.8660254037844386
-0.8660254037844386 0.5000000000000001


Il tipo dei dati può essere specificato come parametro al momento della creazione dell'array.

In [16]:
x = np.array([2, 5, 6], np.int32)
print(x)

[2 5 6]


In [17]:
x = np.array([2, 5, 6], np.float64)
print(x)

[2. 5. 6.]


Accesso alle specifiche righe:

In [18]:
print(rot[0])
print(rot[1])
print(rot[0, :])
print(rot[1, :])

[0.5       0.8660254]
[-0.8660254  0.5      ]
[0.5       0.8660254]
[-0.8660254  0.5      ]


Accesso alle specifiche colonne:

In [19]:
print(rot[:, 0])
print(rot[:, 1])

[ 0.5       -0.8660254]
[0.8660254 0.5      ]


Accesso a sottoinsiemi della matrice (ossia al *minore* della matrice): :

In [10]:
m = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10 , 11, 12]])
print(m)
m1 = m[1:3, 1:3]
print(m1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 6  7]
 [10 11]]


Accesso agli elementi saltandone un certo numero

In [22]:
m = np.array([[1, 2, 3, 4, 5, 6, 7, 8], [9, 10 , 11, 12, 13, 14, 15, 16]])
print(m)
# skip even or odd columns 
me = m[0:2, 0:8:2]
mo = m[0:2, 1:8:2]
print(me)
print(mo)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]
[[ 1  3  5  7]
 [ 9 11 13 15]]
[[ 2  4  6  8]
 [10 12 14 16]]


Accesso a sottoinsiemi in scrittura:

In [23]:
x = np.zeros(10)
print(x)
x[2:5] = 2
print(x)
x[2:5] = [1, 2, 3]
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 2. 2. 2. 0. 0. 0. 0. 0.]
[0. 0. 1. 2. 3. 0. 0. 0. 0. 0.]


Inizializzazione: tutti zeri

In [16]:
x = np.ones((3,2))
print(x)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


Inizializzazione: tutti valori uguali

In [11]:
x = np.full((2,3),2)
print(x)

[[2 2 2]
 [2 2 2]]


Inizializzazione: casuale

In [12]:
r = np.random.rand(3,3)
print(r)

[[0.40243467 0.58207529 0.89458879]
 [0.59485948 0.70133184 0.14887871]
 [0.37443767 0.60970832 0.15567004]]


Matrice identità

In [26]:
i = np.identity(4)
print(i)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Accesso a blocchi in scrittura

In [27]:
i[2:4,0:2] = rot
print(i)

[[ 1.         0.         0.         0.       ]
 [ 0.         1.         0.         0.       ]
 [ 0.5        0.8660254  1.         0.       ]
 [-0.8660254  0.5        0.         1.       ]]


In [28]:
i[0:2,2:4] = rot
print(i)

[[ 1.         0.         0.5        0.8660254]
 [ 0.         1.        -0.8660254  0.5      ]
 [ 0.5        0.8660254  1.         0.       ]
 [-0.8660254  0.5        0.         1.       ]]


Selezione di elementi multipli

In [29]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8])
ev = x[[1, 3, 5, 7]]
od = x[[0, 2, 4, 6]]
print(ev)
print(od)

[2 4 6 8]
[1 3 5 7]


In [30]:
m = np.array([[1, 0, 0, 0], [0, 2, 0, 0], [0, 0, 3, 0], [0, 0, 0, 4]])
diag = m[[0, 1, 2, 3], [0, 1, 2, 3]]
print(diag)

[1 2 3 4]


# Copie: shallow vs deep
La copia di default è *shallow*, ossia viene assegnato un puntatore all'oggetto originale. Per avere una copia diversa dall'ogetto originale bisogna usare il metodo ```copy()```.

In [18]:
a = np.zeros(5)
b = a
print(a, b)
a[2] = 9
print(a,b)

[0. 0. 0. 0. 0.] [0. 0. 0. 0. 0.]
[0. 0. 9. 0. 0.] [0. 0. 9. 0. 0.]


In [31]:
a = np.zeros(5)
b = a.copy()
print(a, b)
a[2] = 9
print(a,b)

[0. 0. 0. 0. 0.] [0. 0. 0. 0. 0.]
[0. 0. 9. 0. 0.] [0. 0. 0. 0. 0.]


# Manipolazione con operazioni matematiche

In sostanza, tutte le operazioni vengono svolte elemento per elemento.

Attenzione! La moltiplicazione tra matrici su puà fare come ```np.matmul(a,b)```, **non** come ```a*b```.

In [32]:
a = np.array([1,2,3])
b = a*2
print(a, b)

[1 2 3] [2 4 6]


Moltiplicazione elemento per elento

In [34]:
a = np.array([1,2,3,4]); b = np.array([3, 4, 5,6])
ab = a*b
print(a, b, ab)

[1 2 3 4] [3 4 5 6] [ 3  8 15 24]


In [36]:
a2 = a**2
print(a, a2)

[1 2 3 4] [ 1  4  9 16]


Sequenza equispaziata tra un valore minimo ed un valore massimo

In [38]:
bins = 10
step = math.pi/bins
theta = np.arange(0, math.pi+step, step)
print(theta)

[0.         0.31415927 0.62831853 0.9424778  1.25663706 1.57079633
 1.88495559 2.19911486 2.51327412 2.82743339 3.14159265]


Possiamo calcolare i valori di una funzione corrispondenti agli elementi che passiamo.

Questa funzione è estremamente utile per fare grafici di una funzione, che di fatto sono curve che passano per una serie di punti forniti dall'utente.

In [39]:
ct = np.cos(theta)
st = np.sin(theta)
np.set_printoptions(precision=4, suppress=True)
print(ct)
print(st)

[ 1.      0.9511  0.809   0.5878  0.309   0.     -0.309  -0.5878 -0.809
 -0.9511 -1.    ]
[0.     0.309  0.5878 0.809  0.9511 1.     0.9511 0.809  0.5878 0.309
 0.    ]


Applicare ripetutamente una funzione. Questa possibilità sfrutta il fatto che python è un interprete. Purché sia definito l'operatore ```**``` (```x**2```), la funzione ```fun``` può essere eseguita.

In [40]:
v = np.array([1, 2, 3, 4, 5])
fun = lambda x: x**2 - 1
f = fun(v)
print(f)

[ 0  3  8 15 24]


Si può definire una funzione che prende come argomento un ```np.array``` e applica ripetutamente un'altra funzione data a ciascun elemento.

In [43]:
def sinus(x):
    return math.sin(x)+math.cos(x)

In [44]:
# l'istruzione che segue dà un errore
f = sinus(x)

TypeError: only size-1 arrays can be converted to Python scalars

In [45]:
vfunc = np.vectorize(sinus)
f = vfunc(v)
print(f)

[ 1.3818  0.4932 -0.8489 -1.4104 -0.6753]


# Algebra lineare

Prodotto tra matrici

In [46]:
a = np.array([[1, 2, 3],[4, 5, 6]])
b = np.array([[1,2], [3, 4], [5,6]])
ab = np.matmul(a,b)
print(ab)

[[22 28]
 [49 64]]


Determinante

In [47]:
det = np.linalg.det(ab)
print(det)
print(22*64-28*49)

35.99999999999982
36


Matrice inversa

In [48]:
inv = np.linalg.inv(ab)
print(inv)

[[ 1.7778 -0.7778]
 [-1.3611  0.6111]]


Calcolo degli autovalori ed autovettori

In [49]:
a = np.array([[1, 2, 0, 0],[2, 1, 0, 0], [0, 0, 2, 3],[0, 0, 3, 2]])
print(a)

[[1 2 0 0]
 [2 1 0 0]
 [0 0 2 3]
 [0 0 3 2]]


In [50]:
w, v = np.linalg.eig(a)
print(w)
print(v)

[ 3. -1.  5. -1.]
[[ 0.7071 -0.7071  0.      0.    ]
 [ 0.7071  0.7071  0.      0.    ]
 [ 0.      0.      0.7071 -0.7071]
 [ 0.      0.      0.7071  0.7071]]


# Principali indicatori statistici

In seguito daremo una più precisa definizione degli indicatori statistici. Quella che segue è solo un'anteprima.

In [51]:
x = np.random.rand(10)
print(x.min(),x.max())
print("sum: ", x.sum())
print("mean: ", x.sum()/x.shape[0])
print("mean: ", x.mean())
print("mean sq: ", (x**2).mean())
print("variance: ", (x**2).mean()-x.mean()**2)
print("variance: ", x.var())
print("std. dev: ", math.sqrt(x.var()))
print("std. dev: ", x.std())

0.07121834324280851 0.8660774281738725
sum:  4.997330961436707
mean:  0.4997330961436707
mean:  0.4997330961436707
mean sq:  0.31202938632019406
variance:  0.06229621893885487
variance:  0.06229621893885475
std. dev:  0.24959210512124527
std. dev:  0.24959210512124527


In [52]:
m = np.random.rand(6, 4)
print(m)
print("sum: ", m.sum())
print("sum cols: ", m.sum(axis = 0))
print("sum rows: ", m.sum(axis = 1))

[[0.8513 0.6132 0.307  0.7332]
 [0.8113 0.1391 0.0052 0.973 ]
 [0.8447 0.8058 0.1657 0.0507]
 [0.3891 0.5471 0.8676 0.4248]
 [0.0149 0.497  0.7014 0.3084]
 [0.2282 0.4671 0.4124 0.5661]]
sum:  11.724416919835566
sum cols:  [3.1395 3.0692 2.4594 3.0562]
sum rows:  [2.5046 1.9287 1.8669 2.2286 1.5217 1.6738]


# Altre manipolazioni

In [53]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
v = np.vstack([v1,v2])
print(v)

[[1 2 3 4]
 [5 6 7 8]]


In [41]:
h1 = np.array([[1,2], [3, 4]])
h2 = np.array([[5, 6, 7], [8, 9, 10]])
h = np.hstack([h1, h2])
print(h)

[[ 1  2  5  6  7]
 [ 3  4  8  9 10]]


# Input da file
I numeri sono di default interpretati come float

In [42]:
m = np.genfromtxt('data/np-data.txt', delimiter=',')
print(m)
m = m.astype('int32')
print(m)

[[1. 2.]
 [3. 4.]
 [5. 6.]
 [7. 8.]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


# Condizioni booleane

In [43]:
(m > 3)

array([[False, False],
       [False,  True],
       [ True,  True],
       [ True,  True]])

In [44]:
((m > 3) & (m < 7))

array([[False, False],
       [False,  True],
       [ True,  True],
       [False, False]])

Selezione degli elementi secondo una condizione

In [60]:
x = np.random.rand(10)
x1 = x[x>0.5]
print(x)
print(x1)

[0.3483 0.2992 0.6374 0.5438 0.1475 0.3256 0.5209 0.1917 0.4744 0.3386]
[0.6374 0.5438 0.5209]
